spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=${AI_MODEL:gpt-4o-mini}